# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: 
    - adf_publish
    exclude:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  environment: qa

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise – MPN(93ddb8b3-ddb9-4d1c-ba59-421456e65538)'
    subscriptionId: '93ddb8b3-ddb9-4d1c-ba59-421456e65538'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ADF-Test'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'JoshTestADF1/ARMTemplateForFactory.json'
    csmParametersFile: 'JoshTestADF1/ARMTemplateParametersForFactory.json'
    overrideParameters: '-factoryName "JoshTestADF1-$(environment)"'
    deploymentMode: 'Incremental'